DATASET_DIRECTORY: "data"
RAW_DATASET_DIRECTORY: "raw"
INTERIM_DATASET_DIRECTORY: "interim"
PROCESSED_DATASET_DIRECTORY: "processed"
TRAIN_DATASET_FILE: "Data_Train.xlsx"
TEST_DATASET_FILE: "Data_Test.xlsx"

ARTIFACT_DIRECTORY: "artifacts"
PREPROCESSOR_FILE: 'preprocessor.joblib'

MODEL_DIRECTORY: "models"
MODEL_FILE: "model.joblib"