Numerical_Columns:
  - Total_Stops
  - Duration_Hours
  - Duration_Mins
  - Journey_Day
  - Journey_Month
  - Dep_Hour
  - Dep_Min
  - Arrival_Hour
  - Arrival_Minute

Categorical_Columns:
  - Airline
  - Source
  - Destination


Interim_Column_Names:
  - Airline
  - Source
  - Destination
  - Total_Stops
  - Duration_Hours
  - Duration_Mins
  - Journey_Day
  - Journey_Month
  - Dep_Hour
  - Dep_Min
  - Arrival_Hour
  - Arrival_Minute

Processed_Column_Names:
  - "Total_Stops"
  - "Duration_Hours"
  - "Duration_Mins"
  - "Journey_Day"
  - "Journey_Month"
  - "Dep_Hour"
  - "Dep_Min"
  - "Arrival_Hour"
  - "Arrival_Minute"
  - "Airline_Air India"
  - "Airline_GoAir"
  - "Airline_IndiGo"
  - "Airline_Jet Airways"
  - "Airline_Multiple carriers"
  - "Airline_Others"
  - "Airline_SpiceJet"
  - "Airline_Vistara"
  - "Source_Chennai"
  - "Source_Delhi"
  - "Source_Kolkata"
  - "Source_Mumbai"
  - "Destination_Cochin"
  - "Destination_Delhi"
  - "Destination_Hyderabad"
  - "Destination_Kolkata"
  - "Destination_New Delhi"

Total_Stops:
  "non-stop": 0
  "1 stop": 1
  "2 stops": 2
  "3 stops": 3
  "4 stops": 4


Other_Airlines:
  - "Multiple carriers Premium economy"
  - "Jet Airways Business"
  - "Trujet"
  - "Vistara Premium economy"

Airlines:
  - "Air Asia"
  - "Air India"
  - "GoAir"
  - "Indigo"
  - "Jet Airways"
  - "Jet Airways Business"
  - "Multiple carriers"
  - "Multiple carriers Premium economy"
  - "SpiceJet"
  - "Trujet"
  - "Vistara"
  - "Vistara Premium economy"

Source:
  - "Banglore"
  - "Chennai"
  - "Delhi"
  - "Kolkata"
  - "Mumbai"

Destination:
  - "Banglore"
  - "Cochin"
  - "Delhi"
  - "Hyderabad"
  - "Kolkata"
  - "New Delhi"

